name: Add package to repo

on:
  repository_dispatch
    
jobs:
  add_torepo:
    runs-on: ubuntu-latest
    steps:
      - name: Check request
        run: |
          echo ${{github.event.client_payload}}
